# Generated by Django 3.1 on 2020-09-11 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userjobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_Name', models.CharField(default='Job_Name', max_length=50)),
                ('Description', models.TextField(default='Job_Desc', max_length=200)),
                ('Expected_Salary', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('Exp', models.IntegerField(default=0)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orgjobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_Name', models.CharField(default='Job_Name', max_length=50)),
                ('Description', models.TextField(default='Job_Desc', max_length=200)),
                ('Salary', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('Exp', models.IntegerField(default=0)),
                ('No_of_openings', models.IntegerField(default=0)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
