# Generated by Django 3.1 on 2020-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seek', '0002_auto_20200912_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Contact',
            field=models.CharField(default='111111111111', max_length=12),
        ),
    ]
