# Generated by Django 3.1 on 2020-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seek', '0003_userprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='Contact_Number',
            field=models.CharField(default='111111111111', max_length=12),
        ),
    ]
