# Generated by Django 3.1 on 2020-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seek', '0004_org_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Residence',
            field=models.CharField(default='India', max_length=60),
        ),
    ]
