# Generated by Django 3.1 on 2020-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seek', '0005_userprofile_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='Address',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
